### PR TITLE
Statlines and Page References

### PR DESCRIPTION
**Pull request by GT3000**
Updated all existing statlines for models and added page references to every item.

Additionally updated to 2.02.04

### CODE REVIEW

**Comment by mattcaron** [comment]
Thanks for the PR, but can you unzip this (so it's a .cat file rather than a .catz)? That way, the XML shows up in a diff. That's also that the original file is.

Thanks.

**Comment by GT3000** [comment]
Done, I believe. Need to figure how to added new factions/units as I'd like to incorporate the rest of the companion books.

**Review by mattcaron — CHANGES_REQUESTED** [review]
If you look at the diff, this isn't a valid .cat file. This is some other web page content.

I'll just unzip your catz file and do it myself, crediting you.

**Comment by mattcaron** [comment]
Also, what factions did I miss from the source books?

**Comment by mattcaron** [comment]
I've unzipped the cat file and committed it in https://github.com/mattcaron/battlescribe-this_is_not_a_test/commit/4293d319ee4dbd408cfdbbdc614f3c4e81ee1780

**Pull request closed without merging**
